### ISSUE TITLE
Typo on the README & project health

### ISSUE THREAD

**Issue by williamdes** [smallnest/weighted-rs#2]
Hi
Thank for this nice project !
Is this project still alive ?

It should be `weighted_rs` not `weighted-rs` on the README

**Comment by smallnest** [comment]
Yes, it is alive.
Please submit your issues if you find any problems about it, thanks.

**Comment by williamdes** [comment]
> Yes, it is alive. Please submit your issues if you find any problems about it, thanks.

Awesome

Thank you for https://github.com/smallnest/weighted-rs/commit/2965f4a0b9cbda074f2e24a0891a80d69a31e495
